[package]
name = "maplibre-legend-prueba"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
maplibre-legend = { path = ".." }
# maplibre-legend = { path = "..", default-features = false, features = ["sync"] }
